server:
  port: 8080

spring:
  application:
    name: api-gateway

  datasource:
    url: jdbc:mysql://localhost:3306/jwt
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    gateway:
      routes:
        - id: example-service
          uri: http://localhost:8081
          predicates:
            - Path=/example/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
