server:
  port: 8080
  forward-headers-strategy: framework

logging:
  level:
    web: debug
    io:
      swagger: debug

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: auth-service
          predicates:
            - Path=/auth/users
            - Method=POST
          filters:
            - RewritePath=/auth/(?<segment>.*), /$\{segment}
          uri: http://localhost:8081

        - id: auth-service
          predicates:
            - Path=/auth/login
          filters:
            - RewritePath=/auth/(?<segment>.*), /$\{segment}
            - AuthFilter
          uri: http://localhost:8081

        - id: auth-service
          predicates:
            - Path=/auth/users
            - Method=PUT
          filters:
            - RewritePath=/auth/(?<segment>.*), /$\{segment}
            - AuthFilter
          uri: http://localhost:8081

        - id: auth-service
          predicates:
            - Path=/auth/swagger-ui/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /$\{segment}
          uri: http://localhost:8081

        - id: auth-service
          predicates:
            - Path=/auth/v3/api-docs/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /$\{segment}
          uri: http://localhost:8081

        - id: order-service
          predicates:
            - Path=/orders/**
          filters:
            - RewritePath=/orders/(?<segment>.*), /$\{segment}
          uri: http://localhost:8083

        - id: product-service
          predicates:
            - Path=/products/**
          filters:
            - RewritePath=/products/(?<segment>.*), /$\{segment}
          uri: http://localhost:8082

springdoc:
  api-docs:
    enabled: true
    groups:
      enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    url: /v3/api-docs
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /auth/v3/api-docs
        name: Auth Service
      - url: /orders/v3/api-docs
        name: Order Service
      - url: /products/v3/api-docs
        name: Product Service
